--Jesse Martino
--Deliverable II
--Database Systems BCS 260

CREATE TABLE MEMBER
(MemberID Int,
CONSTRAINT 		MEMBER_PK    PRIMARY KEY(MemberID)
)
;

CREATE TABLE GENRE
(GenreID Int,
GenreName Char(20),
GenereDescription VARCHAR(100), 
CONSTRAINT 		GENRE_PK    PRIMARY KEY(GenreID)
)
;

CREATE TABLE RECORDCO
(RecordCoID Int,
CONSTRAINT 		RECORD_PK    PRIMARY KEY(RecordCoID)
)
;

CREATE TABLE ALBUM
(AlbumID Int,
RecordCoID Int,
CONSTRAINT 		ALBUM_PK    PRIMARY KEY(AlbumID),

	CONSTRAINT 		ALBUM_RECORDCO_FK    FOREIGN KEY(RecordCoID)
						REFERENCES RECORDCO(RecordCoID)
							ON UPDATE CASCADE
							ON DELETE NO ACTION
 )
;

CREATE TABLE ARTIST_GROUP
(ArtistID Int,
ArtistName Char(40),
RecordCoID Int,
CONSTRAINT 		ARTIST_GROUP_PK    PRIMARY KEY(ArtistID),

	CONSTRAINT 		RECORDCO_RECORD_FK    FOREIGN KEY(RecordCoID)
						REFERENCES RECORDCO(RecordCoID)
							ON UPDATE CASCADE
							ON DELETE NO ACTION
)
;

CREATE TABLE SONG
(SongID Int,
SongLength Char(10),
SongName Char(30),
SongProducer Char(20),
ArtistID Int,
CONSTRAINT		SONG_PK		PRIMARY KEY(SongID),

	CONSTRAINT		ARTIST_GROUP_FK		FOREIGN KEY(ArtistID)
							REFERENCES ARTIST_GROUP(ArtistID)
							ON UPDATE CASCADE
							ON DELETE NO ACTION
)
;
				
